[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = 'source ~/.vim/nvim/rc/unite.rc.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
let g:user_emmet_mode = 'i'
let g:user_emmet_leader_key = '<C-E>'
let g:user_emmet_complete_tag = 1
let g:user_emmet_settings = {
  \ 'variables': {
  \   'lang': 'ja'
  \ },
  \ 'identation': '    '
\ }
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
hook_source = 'source ~/.vim/nvim/rc/complete.rc.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/nvim/rc/snippet.rc.vim'

# markdown ============================
[[plugins]]
repo = 'rhysd/github-complete.vim'
on_ft = ['markdown', 'gitcommit']
hook_add = '''
let g:thub_complete_emoji_japanese_workaround = 1
'''

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

# css =================================
[[plugins]]
repo = 'AtsushiM/sass-compile.vim'
on_ft = 'css'
depends = 'search-parent.vim'
hook_add = '''
let g:sass_complite_auto = 0
let g:sass_complite_file = ['sass', 'scss']
let g:sass_complite_dir = ['css', 'stylesheets']
'''

[[plugins]]
repo = 'AtsushiM/search-parent.vim'

[[plugins]]
repo = 'stephenway/postcss.vim'
on_ft = 'css'

# javascript ==========================
[[plugins]]
repo = 'carlitux/deoplete-ternjs'
build = 'npm install -g tern'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

