[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = 'source ~/.vim/nvim/rc/unite.rc.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
let g:user_emmet_mode = 'i'
let g:user_emmet_leader_key = '<C-E>'
let g:user_emmet_complete_tag = 1
let g:user_emmet_settings = {
  \ 'variables': {
  \   'lang': 'ja'
  \ },
  \ 'identation': '    '
\ }
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
depends = 'context_filetype.vim'
hook_source = 'source ~/.vim/nvim/rc/complete.rc.vim'
# hook_post_source = 'call deoplete#enable()'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = 'snippet'
depends = 'neosnippet-snippets'
hook_source = 'source ~/.vim/nvim/rc/snippet.rc.vim'

