[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = 'source ~/.vim/nvim/rc/unite.rc.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'osyo-manga/unite-filetype'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_source = 'denite.nvim'
hook_source = 'source ~/.vim/nvim/rc/unite.rc.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = 'source ~/.vim/nvim/rc/deoplete.rc.vim'

[[plugins]]
repo = "Shougo/denite.nvim"
depends = 'neomru.vim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/nvim/rc/denite.rc.vim'
hook_add = '''
nnoremap  [denite]  <Nop>
nmap      <Leader>n [denite]
nnoremap  [denite]a :<C-u>Denite buffer file_mru directory_rec<CR>
nnoremap  [denite]f :<C-u>DeniteProjectDir file_mru directory_rec<CR>
nnoremap  [denite]h :<C-u>Denite register unite:register neoyank<CR>
nnoremap  [denite]o :<C-u>Denite unite:outline<CR>
nnoremap  [denite]t :<C-u>Denite filetype<CR>
'''

