#======================================
# Utility
#
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_source = 'source ~/.vim/nvim/rc/vimfiler.rc.vim'

[[plugins]]
repo = 'junegunn/fzf'
depends = 'fzf'
hook_source = 'source ~/.vim/nvim/rc/fzf.rc.vim'

repo = 'tsuyoshiwada/slack-memo-vim'
depends = 'mattn/webapi-vim'
hook_source = '''
if filereadable(expand('$HOME/.slack_memo_profile'))
  source $HOME/.slack_memo_profile
endif
'''
hook_add = '''
let g:slack_memo_bot_username = 'weathare'
let g:slack_memo_bot_icon_emoji = ':vim:'
nnoremap sme :split enew<CR>:set ft=markdown<CR>gI
nnoremap smp :SlackMemoPost<CR>
nnoremap sml :SlackMemoList<CR>:set modifiable<CR>
'''

[[plugins]]
repo = 'mattn/gist-vim'
depends = 'mattn/webapi-vim'
hook_add = '''
let g:github_user = "weathare"
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
let g:extra_whitespace_ignored_filetypes = ['unite', 'vimfiler', 'denite']
'''

#=======================================
# Color
#
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'popkirby/lightline-iceberg'
depends = ['lightline.vim', 'iceberg.vim']
hook_source = 'source ~/.vim/nvim/rc/color.rc.vim'

#======================================
# Git
#
[[plugins]]
repo = 'tpope/vim-git'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_enabled = 0

nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR>
nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
'''

[[plugins]]
repo = 'rhysd/committia.vim'
hook_add = '''
let g:committia_hooks = {}
function! g:committia_hooks.edit_open(info)
  setlocal spell

  if a:info.vcs ==# 'git' && getline(1) ==# ''
    startinsert
  end

  imap <buffer><C-j>  <Plug>(committia-scroll-diff-down-half)
  imap <buffer><C-k>  <Plug>(committia-scroll-diff-up-half)
endfunction
'''

#======================================
# Helper
#
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_if = 1

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
map _ <Plug>(operator-replace)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
hook_add = '''
map <silent>sa <Plug>(operator-surround-append)
map <silent>sd <Plug>(operator-surround-delete)
map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap  <C-_> <Plug>(caw:hatpos:toggle)
vmap  <C-_> <plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
vmap <Enter> <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'tpope/vim-endwise'
